### PR TITLE
added changes for k8s pebblo deployment

### PR DESCRIPTION
**Pull request by siddheshwar-more**
Includes -
1. k8s manifest file 
2. readme

### CODE REVIEW

**Comment by srics** [comment]
@siddheshwar-more can you move `k8s-deploy` dir under a top level `deploy` dir? Also, pls consider moving top-level `docker` folder under the new `deploy` dir

**Comment by siddheshwar-more** [comment]
> @siddheshwar-more can you move `k8s-deploy` dir under a top level `deploy` dir? Also, pls consider moving top-level `docker` folder under the new `deploy` dir

@srics  Fixed. Please check.

**Comment by srics** [comment]
> > @siddheshwar-more can you move `k8s-deploy` dir under a top level `deploy` dir? Also, pls consider moving top-level `docker` folder under the new `deploy` dir
> 
> @srics Fixed. Please check.

Looks good. Minor comment, you can drop the `-deploy` for `k8s` dir. Pls rebase/resolve conflict before we can merge this.

**Comment by siddheshwar-more** [comment]
@srics  Opened New PR https://github.com/daxa-ai/pebblo/pull/362

**Pull request closed without merging**
